# Generated by Django 4.2 on 2023-04-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='titel')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='files/%Y/%m/%d/', verbose_name='image')),
                ('create', models.TimeField(auto_now_add=True, verbose_name='create post')),
                ('update', models.TimeField(auto_now=True, verbose_name='create post')),
            ],
        ),
    ]
